/**
 * The flat backdrop, used when the 3D world cannot or should not run.
 *
 * Terrain is tiled from original 16x16 pixel-art blocks in /public/tex
 * (generated by tools/make_textures.py), scaled to 48px and rendered with
 * image-rendering: pixelated so the pixels stay chunky rather than smeared.
 *
 * Layer opacities come from --l-* custom properties which [data-biome] swaps
 * in index.css, so changing section changes the world without React
 * re-rendering anything here.
 */
export default function World2D() {
  return (
    <div className="world" aria-hidden>
      <i className="w-stars" />
      <i className="w-clouds" />
      <i className="w-hills" />
      <i className="w-stone" />
      <i className="w-ench" />
      <i className="w-trees" />
      <i className="w-cherry" />
      <i className="w-grass" />
      <i className="w-dirt" />
      <i className="w-deepslate" />
      <i className="w-planks" />
      <i className="w-ores" />
      <i className="w-torch" />
      <i className="w-torches" />
      <i className="w-glyphs" />
      <i className="w-dim" />
      <i className="w-scrim" />
    </div>
  );
}
